name       : libinput
version    : 1.12.2
release    : 24
source     :
    - https://www.freedesktop.org/software/libinput/libinput-1.12.2.tar.xz : 6b9b95e9b515ace27a5f8a804f3868d39c699cd8fc485fd57aed1739009c1cf1
license    : MIT
component  : desktop.library
summary    : Generic input library
description: |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libudev)
    - pkgconfig(libwacom)
    - pkgconfig(mtdev)
    - pyparsing
setup      : |
    %meson_configure -Ddebug-gui=false \
        -Ddocumentation=false \
        -Dtests=false \
        -Dudev-dir=%libdir%/udev
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
