name       : libinput
version    : 1.7.1
release    : 11
source     :
    - https://www.freedesktop.org/software/libinput/libinput-1.7.1.tar.xz : 2e56bc5bbf7d202dd94e1a5673489ce86fe10b1d4b5145948e9ba15f053247c1
license    : MIT
component  : desktop.library
summary    : Generic input library
description: |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libudev)
    - pkgconfig(libwacom)
    - pkgconfig(mtdev)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
