name       : libinput
version    : 1.4.0
release    : 6
source     :
    - https://www.freedesktop.org/software/libinput/libinput-1.4.0.tar.xz : 76ef10874519d1a67b57e5c68ede06106b9fbf611a3ecf69c84886107c67b420
license    :
    - MIT
summary    : Generic input library
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(libudev)
    - pkgconfig(libevdev)
    - pkgconfig(libwacom)
description: |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
