name       : libinput
version    : 1.15.4
release    : 33
source     :
    - https://www.freedesktop.org/software/libinput/libinput-1.15.4.tar.xz : 9c8b6846d94e374ee4bdb32634e4ac4aa318afc31f9a58fcb545cd3095c745c1 
license    : MIT
component  : desktop.library
summary    : Generic input library
description: |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libudev)
    - pkgconfig(libwacom)
    - pkgconfig(mtdev)
    - pyparsing
setup      : |
    %meson_configure -Ddebug-gui=false \
        -Ddocumentation=false \
        -Dtests=false \
        -Dudev-dir=%libdir%/udev
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
