name        : libinput
version     : 1.1.0
release     : 5
source     :
    - http://www.freedesktop.org/software/libinput/libinput-1.1.0.tar.xz : 673186ea2a0d2b695afaa9758834f9217b175774d9ae222e1b43ff63c663f582
license     :
    - MIT
summary     : Generic input library
builddeps   :
    - pkgconfig(mtdev)
    - pkgconfig(libudev)
    - pkgconfig(libevdev)
description : |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
setup      : |
    %patch -p1 < $pkgfiles/0001-touchpad-serial-synaptics-need-to-fake-new-touches-o.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
