name       : libinput
version    : 1.23.0
release    : 42
source     :
    - https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.23.0/libinput-1.23.0.tar.gz : 7a7c90fbc59f1f65c781a51fa634e4f79e460bf6e16ad68afbe7965d25d09738
license    : MIT
component  : desktop.library
summary    : Generic input library
description: |
    libinput is a library to handle input devices in Wayland compositors and to provide a generic X.Org input driver. It provides device detection, device handling, input device event processing and abstraction so minimize the amount of custom input code compositors need to provide the common set of functionality that users expect.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libudev)
    - pkgconfig(libwacom)
    - pkgconfig(mtdev)
    - pyparsing
    - python-pytest
setup      : |
    %meson_configure -Ddebug-gui=false \
        -Ddocumentation=false \
        -Dtests=false \
        -Dudev-dir=%libdir%/udev
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Empty
    rm -fr $installdir/etc/
check      : |
    %ninja_check
